i fixed the format of the header
chacaa/GeoQuiz pull request #2
Opened 2017-01-25 18:10 UTC by chacaa

I made the app bigger by adding more questions and the possibility to navigate between them (for the moment you only can go forward).

### Related Trello cards:
[[AP - Chapter 2] Android and Model-View-Controller](https://trello.com/c/wOohgOQm)

### Additional Info:
* I also added a toast message when you reach the last question and try to continue with the next one.

### UI preview:
![alt text](http://g.recordit.co/eETQ0l9ng7.gif)

/cc @xmartlabs/android

2017-01-25 18:24 UTC, mirland requested changes

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/module/Question.java
> +
remove space

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/module/Question.java
> +
remove space

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private Question[] questionBank = new Question[] {
We should avoid using Arrays, use a list instead of it

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private Question[] questionBank = new Question[] {
you can use `Arrays.asList`

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private int checkAnswer(String valueButton) {
the name is not right, "Check answer" is not what the function does

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    if (valueButton.toLowerCase().equals(String.valueOf(questionBank[currentIndex].isAnswerTrue()))) {
use the shortest form of return

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private Question[] questionBank = new Question[] {
Also this could grow up very quickly, maybe you should put it in a method

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/module/Question.java
> +  private int textResId;
add `@StringRes` annotation

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +          Toast.makeText(QuizActivity.this, "No more questions for today :)", Toast.LENGTH_SHORT).show();
:+1:

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private int checkAnswer(String valueButton) {
also annotate it with the `@StringRes` annotation

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    if (valueButton.toLowerCase().equals(String.valueOf(questionBank[currentIndex].isAnswerTrue()))) {
http://stackoverflow.com/questions/8898590/short-form-for-java-if-statement

2017-01-25 18:24 UTC, matir91 commented on app/src/main/res/layout/activity_quiz.xml
> -        android:text="@string/question_text"
you shouldn't remove this line, use the tools namespace, `tools:text="@string/question_text"`. The main reason of this is that the layout will be fine in the preview

2017-01-25 18:24 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/module/Question.java
> +  public int getTextResId() {
add `@StringRes` annotation

2017-01-25 18:31 UTC, bryant1410 commented
I recommend following [a format in git commit messages and PRs titles](http://chris.beams.io/posts/git-commit/). I think [Pro Git](https://git-scm.com/book/en/v2) also has recommendations.

2017-01-26 16:35 UTC, diegomedina248 reviewed
Left some comments

2017-01-26 16:35 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/module/Question.java
> +
If you click on the "light bulb" you can edit the template and remove that space there so you don't have to do it manually

2017-01-26 16:35 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/module/Question.java
> +    public Builder() {
Is this constructor necessary? It should exist by default

2017-01-26 16:35 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/module/Question.java
> +    public Builder textResId(int val) {
Prefer to use a more descriptive name for variables whenever possible. I'd use textResId here

2017-01-26 16:35 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/module/Question.java
> +    public Builder answerTrue(boolean val) {
here too

2017-01-26 16:35 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private Question[] questionBank = new Question[] {
I agree, also to reduce the duplicated code

2017-01-26 16:35 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +          Toast.makeText(QuizActivity.this, "No more questions for today :)", Toast.LENGTH_SHORT).show();
The string should be made a resource

2017-01-26 16:35 UTC, diegomedina248 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +        if (currentIndex == questionBank.length - 1) {
just for clarity purposes, consider in these cases extracting this into a new method.
```java
if (isLastQuestion()) {
```
is far more readable.
Just a thought

2017-01-26 17:16 UTC, bryant1410 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/module/Question.java
> +    public Builder() {
Just to provide more context, Java creates by default a public non-args constructor to all classes that don't declare a constructor.

2017-01-26 17:29 UTC, chacaa commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/module/Question.java
> +    public Builder() {
Yep! I forgot that, thanks!

2017-01-26 17:31 UTC, chacaa commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +        if (currentIndex == questionBank.length - 1) {
I'll keep it in mind for future commits, thanks!

2017-01-26 17:40 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/module/Question.java
> +    public Builder() {
BTW: it's autogenerated code :)

2017-01-26 17:41 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +          Toast.makeText(QuizActivity.this, "No more questions for today :)", Toast.LENGTH_SHORT).show();
yes! my bad!

2017-01-26 18:44 UTC, mirland requested changes

2017-01-26 18:44 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private List<Question> questionBank = new ArrayList<>();
add `@NonNull`

2017-01-26 18:44 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    addQuestion();
what do you think of naming it `setupQuestions` ?

2017-01-26 18:44 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +            nextButton.setEnabled(false);
you can put something like `nextButton.setEnabled(!isLastQuestion())` and remove the first if of the bock

2017-01-26 18:44 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +            nextButton.setEnabled(false);
the same in `prevButton`

2017-01-26 18:44 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private int obtainAnswerValue(String valueButton) {
add `@NonNull` in the parameter

2017-01-26 18:44 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    int currentIndexAux = currentIndex;
you should avoid naming variables with aux prefix

2017-01-26 18:44 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    this.questionBank.add(currentIndexAux,
you don't need put the index, you can remove `currentIndexAux`

2017-01-26 18:44 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +
remove space

2017-01-26 18:44 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    this.questionBank.add(currentIndexAux,
remove this, it is not necessary

2017-01-26 18:44 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private List<Question> questionBank = new ArrayList<>();
avoid putting `Bank` or something like that. Call it as `questions`. Also in some case you can use `questionList`

2017-01-26 18:44 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +        Toast.makeText(QuizActivity.this, obtainAnswerValue(falseButton.getText().toString()), Toast.LENGTH_SHORT).show();
what do you think of putting this sentence (and all the similar sentences) in a function? something like `private void showToast(@NonNull String message)`

2017-01-26 18:45 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private List<Question> questionBank = new ArrayList<>();
https://github.com/xmartlabs/Android-Style-Guide#field-method-variable-and-parameter-names

2017-01-26 18:51 UTC, chacaa commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    addQuestion();
I thought in that name but I'm afraid that maybe someone could get confuse because of the other method that I called setupQuestion

2017-01-26 18:52 UTC, chacaa commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +            nextButton.setEnabled(false);
I'll check it, thanks!

2017-01-26 18:53 UTC, chacaa commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +        Toast.makeText(QuizActivity.this, obtainAnswerValue(falseButton.getText().toString()), Toast.LENGTH_SHORT).show();
That isn't a bad idea at all! Thanks!

2017-01-26 18:55 UTC, chacaa commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    int currentIndexAux = currentIndex;
What do you suggest then? Something like listIndex instead?

2017-01-26 18:55 UTC, chacaa commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    this.questionBank.add(currentIndexAux,
Do you mean the blanc space?

2017-01-26 18:59 UTC, chacaa commented
I forgot to add images to the next and pre buttons. I'll try to add it today if I can.

2017-01-26 19:04 UTC, chacaa commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private List<Question> questionBank = new ArrayList<>();
done!

2017-01-27 14:18 UTC, mirland requested changes

2017-01-27 14:18 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +  private List<Question> questionList = new ArrayList<>();
it's ok, but in the future use `questions`. [`If you need to name a List of activities for example, just name it activities`]
(https://github.com/xmartlabs/Android-Style-Guide?files=1#field-method-variable-and-parameter-names)

2017-01-27 14:18 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    return (valueButton.toLowerCase().equals(String.valueOf(questionList.get(currentIndex).isAnswerTrue()))) ?
remove the `()`

2017-01-27 14:18 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    this.questionList.add(listIndex,
remove `this`

2017-01-27 14:18 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    this.questionList.add(listIndex,
remove the index, it's not necessary

2017-01-27 14:21 UTC, matir91 commented on app/src/main/java/com/xmartlabs/scasas/geoquiz/ui/QuizActivity.java
> +    return (valueButton.toLowerCase().equals(String.valueOf(questionList.get(currentIndex).isAnswerTrue()))) ?
fix indentation too

2017-01-27 15:55 UTC, mirland approved these changes

2017-01-27 17:08 UTC, mirland approved these changes

2017-01-27 17:18 UTC, merged